"""add initial traffic

Revision ID: 8f29a226b288
Revises: b8adda3a1e58
Create Date: 2026-06-03 01:59:53.391570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f29a226b288'
down_revision: Union[str, None] = 'b8adda3a1e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('initial_traffic', sa.BigInteger(), nullable=True, server_default='0'))
    # Backfill existing admins: set initial_traffic = traffic (best we can do for existing rows)
    op.execute('UPDATE admins SET initial_traffic = traffic')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'initial_traffic')
    # ### end Alembic commands ###
